services:
  aurora-dsql:
    image: postgres:16
    shm_size: 512mb
    container_name: forma-postgres
    environment:
      POSTGRES_DB: forma
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - forma-local
  rustfs:
    image: rustfs/rustfs:latest
    container_name: forma-s3-local
    ports:
      - '19000:9000'
      - '19001:9001'
    volumes:
      - './rustfs/s3:/data'
      - './rustfs/log:/log'
    environment:
      - RUSTFS_ACCESS_KEY=minio
      - RUSTFS_SECRET_KEY=minio_password
      - RUSTFS_CONSOLE_ENABLE=true
    networks:
      - forma-local

networks:
  forma-local:
    driver: bridge
    name: forma-local
